import type {City} from "./cities";
import {buildCityContentProfile} from "./city-content-profile";
import type {Panchang} from "./panchang";

type Fact={label:string;value:string;note?:string};

export type DailyCityContext={
  title:string;
  body:string;
  secondaryBody:string;
  facts:Fact[];
};

function clockMinutes(value:string){const [h,m]=value.split(":").map(Number);return Number.isFinite(h)&&Number.isFinite(m)?h*60+m:0;}
function daylight(data:Panchang){const start=clockMinutes(data.sunrise),end=clockMinutes(data.sunset);return end>=start?end-start:end+1440-start;}
function phase(minutes:number){if(minutes<360)return "pre-six sunrise";if(minutes<390)return "early sunrise";if(minutes<420)return "mid-morning-edge sunrise";return "late sunrise";}
function transitionBand(time:string,sunrise:string,sunset:string){const t=clockMinutes(time),rise=clockMinutes(sunrise),set=clockMinutes(sunset),span=Math.max(1,set-rise),share=(t-rise)/span;if(share<0.2)return "opening daylight";if(share<0.4)return "morning";if(share<0.6)return "midday";if(share<0.8)return "afternoon";return "late-day or post-sunset";}
function hash(slug:string){let value=41;for(let i=0;i<slug.length;i++)value=(value*149+slug.charCodeAt(i)*(i+5))%99991;return value;}
function wordsMinutes(minutes:number){if(minutes<710)return "compact";if(minutes<735)return "moderate-short";if(minutes<755)return "balanced";if(minutes<780)return "moderate-long";return "extended";}

const cityLens:Record<string,string>={
  mumbai:"Mumbai's daily distinction comes from a maritime Konkan setting beside the Arabian Sea. The useful contrast is not simply west versus east: the metro combines a strongly west-shifted civil solar clock with a coastal latitude and an urban shoreline horizon. On boundary-sensitive dates, that means the local dawn checkpoint can keep a Tithi or Nakshatra active after an eastern city has already crossed into the next state. The result should be read as a Mumbai morning sequence, not a generic Maharashtra schedule.",
  delhi:"Delhi is a northern continental-plains reference rather than a coastal or plateau proxy. Its Yamuna-side latitude gives a broader seasonal swing in day length, while its longitude places the solar clock west of India's central meridian but not as far west as Gujarat or Rajasthan. For daily Panchang reading, the important feature is the combination of northern seasonality and a metropolitan inland dawn. A transition near sunrise can therefore classify the Delhi date differently from both nearby western cities and lower-latitude southern metros.",
  bengaluru:"Bengaluru's timing identity comes from the elevated southern Deccan rather than from either Indian coast. The city has a lower-latitude daylight regime, but the plateau position and inland longitude give it a clock pattern distinct from Chennai, Hyderabad and Pune. Its daily Panchang should therefore be understood as a highland-southern reference: relatively modest seasonal daylight change, no coastal sunrise proxy, and locally computed dawn boundaries that matter when Tithi or Nakshatra turnover occurs close to the start of the solar day.",
  hyderabad:"Hyderabad sits in the interior Telangana Deccan, giving it a middle-southern clock position between strongly western and strongly eastern Indian cities. It is neither a west-coast timing substitute nor a Bay-of-Bengal one. The city's local dawn, plateau latitude and inland longitude combine into a useful central-Deccan reference. On this page that matters because Rahu placement, Choghadiya boundaries and lunar hand-offs are all attached to Hyderabad's own daylight geometry, not to a statewide or national fixed-clock schedule.",
  ahmedabad:"Ahmedabad is one of the clearest western-clock references in the phase-one city set. Its Sabarmati setting in north-central Gujarat produces later IST placement for sunrise-derived periods than eastern India, while its latitude also creates more seasonal daylight movement than lower-latitude western-coast cities. The daily page should therefore be read as a dry inland western profile: later civil solar timing, a northern-Gujarat day-length pattern and local sunrise boundaries that can keep the opening lunar state active longer by the clock than in cities farther east.",
  chennai:"Chennai provides a low-latitude east-coast frame on the Coromandel Coast. Its sunrise-derived intervals typically sit earlier on the IST clock than western Indian cities, while seasonal day-length variation is comparatively restrained. That combination makes Chennai useful as an opposite reference to Ahmedabad, Mumbai or Pune: the same weekday sequence can appear at noticeably earlier civil times. Daily lunar transitions must therefore be tied to Chennai's own dawn and sunset, especially when a Tithi or Nakshatra boundary sits near the morning edge of the local solar day.",
  kolkata:"Kolkata is a strongly east-shifted civil-solar reference on the lower Hooghly and Bengal delta. Sunrise and other daylight-derived intervals appear much earlier by IST than in western metros, while the city's northern-eastern latitude still gives meaningful seasonal day-length change. A Kolkata Panchang date can therefore move into a new sunrise-state sooner on the civil clock than Mumbai, Ahmedabad or Rajkot. The page's local value lies in preserving that eastern dawn checkpoint and the transition order that follows from it instead of reusing an all-India timetable.",
  surat:"Surat combines a western civil solar clock with a lower Gujarat latitude and Tapi-basin setting near the Gulf of Khambhat. It is geographically and temporally distinct from both Ahmedabad to the north and Mumbai farther south. The daily Panchang lens is therefore a western coastal-basin one: later IST sunrise-derived timing, but a different day-length profile from Ahmedabad and a different local coordinate from the Konkan metros. Boundary-sensitive lunar states should be interpreted from Surat's own dawn rather than inferred from another Gujarat city.",
  pune:"Pune is an inland western-Deccan reference on the plateau east of the Sahyadris. Its local solar clock remains clearly west-shifted by IST, yet it is not interchangeable with Mumbai because the inland coordinate, elevation and plateau setting produce their own sunrise and sunset sequence. The daily page is best read as a plateau-western profile: later civil timing than central India, stronger inland character than the Konkan coast and locally computed lunar boundaries that can diverge from Mumbai on dates where the transition lies close to dawn.",
  jaipur:"Jaipur's daily frame belongs to the eastern Rajasthan interior near the Aravalli region. It combines a northern latitude with a western solar clock, so both civil-time lateness and seasonal day-length variation are important parts of the local signature. This is different from Gujarat's lower latitudes and Delhi's more easterly position. For Panchang interpretation, Jaipur acts as a northern-western inland reference: local sunrise controls the opening Tithi and Nakshatra state, while the longer seasonal daylight swing changes where weekday-derived intervals fall through the year.",
  lucknow:"Lucknow lies in the Awadh sector of the central Gangetic plain and sits much nearer India's standard-meridian solar clock than the western metros. Its northern-plains latitude still gives substantial seasonal day-length change, but the civil solar timing is more central. That makes Lucknow a useful midpoint in the network: neither strongly west-delayed nor strongly east-advanced. The daily Panchang should therefore preserve its own sunrise checkpoint, because a boundary near dawn can separate Lucknow from Delhi, Jaipur, Patna or Varanasi even when the civil calendar date is identical.",
  kanpur:"Kanpur's Ganga-corridor position gives it a central Uttar Pradesh timing frame that is close to, but not identical with, Lucknow. The distinction matters most around sunrise, where even a modest longitude difference can decide whether a Tithi or Nakshatra has already turned over. Kanpur's daily profile is therefore one of fine-grained local separation rather than dramatic east-west contrast. Its page should be read as a river-plain dawn checkpoint with northern seasonality, not as a duplicate of a nearby city simply because many midday values look similar.",
  nagpur:"Nagpur sits near India's geographic centre in the Vidarbha plateau and therefore occupies a comparatively central solar-clock position. Its latitude is also intermediate between the northern plains and the southern peninsula, producing a balanced seasonal daylight regime. The city is valuable as a central-Deccan reference: it avoids the extreme late civil timing of far-western cities and the early timing of Bengal or Assam. Daily Panchang boundaries are still local, however, so Nagpur's sunrise state should not be replaced by Bhopal, Raipur or Hyderabad when transitions fall close to dawn.",
  indore:"Indore belongs to the Malwa plateau in western Madhya Pradesh, combining an inland plateau setting with a moderately west-shifted civil solar clock. It sits east of the strongest Gujarat delay but west of the central-meridian cities, creating a characteristic inland-western timing band. The daily Panchang lens is therefore neither coastal nor central. Its local sunrise determines the opening lunar state, and its daylight span positions Rahu and Choghadiya differently from Ahmedabad, Bhopal or Nagpur even when the weekday sequence itself is shared.",
  thane:"Thane shares the broad Mumbai metropolitan region but represents a different north-eastern Konkan coordinate. That distinction is deliberately preserved because daily Panchang classification can change on dates where Tithi or Nakshatra turnover sits close to sunrise. Thane's page is therefore not intended as a duplicate Mumbai timetable: the metropolitan context is similar, yet the local dawn, sunset and derived weekday intervals are computed independently. The useful semantic signal is precisely that near-neighbour comparison, where small coordinate differences can matter more than large regional labels.",
  bhopal:"Bhopal's central Madhya Pradesh setting places it between western-delay cities and the standard-meridian side of India. The lake-and-plateau geography gives a central-inland reference with neither coastal influence nor a strongly eastern civil clock. Its daily Panchang is useful because it captures a transitional timing zone: sunrise-derived periods are earlier than Indore or Ahmedabad but later than cities farther east, while northern-central latitude still produces clear seasonal daylight movement. Boundary-sensitive lunar states therefore need Bhopal's own dawn checkpoint rather than a generic central-India value.",
  visakhapatnam:"Visakhapatnam combines Bay-of-Bengal longitude with a lower-latitude setting where the Eastern Ghats meet the coast. Its solar clock is distinctly east-shifted, so sunrise-derived Panchang periods appear earlier by IST than in central or western India. At the same time, its tropical latitude gives a different annual daylight pattern from Kolkata. The daily page should therefore be read as a lower-latitude eastern coastal profile: early civil solar timing, coastal dawn geometry and local lunar boundary checks that are not interchangeable with either Chennai or the Bengal delta.",
  patna:"Patna sits on the south bank of the Ganges in Bihar, east of India's standard-meridian zone and within a northern Gangetic daylight regime. This gives it an earlier civil solar clock than Lucknow or Delhi while retaining stronger seasonal day-length variation than lower-latitude eastern cities. The local Panchang signature is therefore north-eastern river-plain timing: earlier dawn by IST, meaningful seasonal change and boundary-sensitive lunar states tied to Patna's own sunrise. It should not be collapsed into Varanasi or Kolkata simply because all three lie east of central India.",
  vadodara:"Vadodara occupies central Gujarat between Ahmedabad and Surat, both geographically and in solar timing. That intermediate position is useful because it demonstrates why statewide Panchang substitution is weak: the city keeps a distinctly western IST clock while retaining its own Vishwamitri-basin latitude and sunrise boundary. The daily page acts as a central-Gujarat reference, with later sunrise-derived periods than central India but a local dawn different from both northern Ahmedabad and lower-latitude Surat. Near-boundary Tithi and Nakshatra states are therefore computed independently.",
  varanasi:"Varanasi lies on the middle Ganges in eastern Uttar Pradesh, close to the standard-meridian side of India's solar-clock geography. Its daily timing is earlier than Jaipur, Delhi or Gujarat but not as strongly east-shifted as Kolkata or Guwahati. Combined with a northern latitude, that produces an eastern-Gangetic profile with clear seasonal daylight movement. For Panchang reading, the important distinction is the local dawn checkpoint on the Ganges corridor: Tithi and Nakshatra states are attached to Varanasi's sunrise rather than inferred from Prayagraj, Patna or a national calendar."
};

export function buildDailyCityContext(city:City,data:Panchang):DailyCityContext{
  const profile=buildCityContentProfile(city);
  const key=hash(city.slug);
  const dayMinutes=daylight(data);
  const tithiBand=transitionBand(data.tithiEnd,data.sunrise,data.sunset);
  const nakshatraBand=transitionBand(data.nakshatraEnd,data.sunrise,data.sunset);
  const good=data.dayChoghadiya.filter(item=>item.effect==="good");
  const firstGood=good[0];
  const lastGood=good[good.length-1];
  const moonState=data.moonIllumination<25?"low-illumination":data.moonIllumination<55?"mid-illumination":data.moonIllumination<80?"brightening":"high-illumination";
  const sunrisePhase=phase(clockMinutes(data.sunrise));
  const dayShape=wordsMinutes(dayMinutes);
  const rahuOffset=Math.max(0,clockMinutes(data.rahu.start)-clockMinutes(data.sunrise));
  const bodyVariant=key%8;
  const secondVariant=Math.floor(key/8)%8;
  const nativeLens=cityLens[city.slug]??profile.dailyContext;

  const bodies=[
    `For ${city.name}, the useful local reading starts with ${profile.geoContext}. This is not just a label on a national table: ${profile.solarClockContext}, and that changes where sunrise-derived intervals sit on the IST clock. Today's ${sunrisePhase} opens a ${dayShape} daylight span. The Tithi boundary falls in the ${tithiBand} band, while the Nakshatra boundary falls in the ${nakshatraBand} band, so the two lunar clocks occupy different parts of the local day.`,
    `${profile.geoContext} gives ${city.name} its own daily timing frame. The city is ${profile.solarClockContext}, so sunrise, Rahu Kalam and Choghadiya must be read from the local solar day rather than borrowed from another metro. Today's daylight profile is ${dayShape}; the Tithi changes around the ${tithiBand} portion of that span and the Nakshatra changes around ${nakshatraBand}. Together those transitions define the page's local chronology.`,
    `The daily calculation is anchored to ${city.name}'s position in ${profile.geoContext}. Its ${profile.latitudeContext} and ${profile.solarClockContext} produce a civil-time pattern that can differ materially from western, eastern or coastal alternatives. Today begins with a ${sunrisePhase}, develops into a ${dayShape} solar day, and then carries the Tithi and Nakshatra hand-offs through the ${tithiBand} and ${nakshatraBand} parts of daylight respectively.`,
    `Read ${city.name} as a local solar location first: ${profile.geoContext}, ${profile.latitudeContext}, and ${profile.solarClockContext}. That geography determines where sunrise-based Panchang periods land on the clock. On this date the day is ${dayShape}; its lunar structure is split because the Tithi transition belongs to ${tithiBand}, whereas the Nakshatra transition belongs to ${nakshatraBand}. This is the main reason a nearby city's timetable is not interchangeable.`,
    `${city.name}'s Panchang sits inside the timing geometry of ${profile.geoContext}. The solar clock is ${profile.solarClockContext}, while the latitude profile is ${profile.latitudeContext}. Today's local day is ${dayShape}, beginning in a ${sunrisePhase} pattern. Instead of one static lunar label for the full civil date, the Tithi changes in ${tithiBand} and the Nakshatra changes in ${nakshatraBand}, producing a two-step sequence after sunrise.`,
    `The city-specific signal here comes from ${profile.geoContext}. ${city.name} is ${profile.solarClockContext}; therefore the clock placement of Rahu, Choghadiya and lunar transitions is evaluated from this city's own sunrise. The current day has a ${dayShape} daylight span. Tithi turnover sits in ${tithiBand}, Nakshatra turnover in ${nakshatraBand}, which gives the date a local order that cannot be reproduced by changing only the city name.`,
    `Today's page uses ${city.name}'s real geographic frame: ${profile.geoContext}. Because it is ${profile.solarClockContext}, the same weekday can map to visibly different clock times than in another part of India. This date produces a ${dayShape} daylight shape with a ${sunrisePhase}; the Tithi boundary occupies ${tithiBand} while the Nakshatra boundary occupies ${nakshatraBand}. Those two positions are the core local fingerprint for the civil day.`,
    `In ${city.name}, Panchang timing is read through ${profile.geoContext} and a ${profile.latitudeContext}. The city's solar clock is ${profile.solarClockContext}, so locally derived intervals remain tied to its own sunrise and sunset. Today the solar span is ${dayShape}. The Tithi exits during ${tithiBand}; the Nakshatra exits during ${nakshatraBand}. That separation turns the page from a static daily label set into a location-specific timeline.`
  ];

  const secondary=[
    `Rahu begins ${rahuOffset} minutes after sunrise. The daytime Choghadiya sequence contains ${good.length} favorable-labelled periods${firstGood&&lastGood?`, opening with ${firstGood.name} and closing with ${lastGood.name}`:""}. The Moon is in a ${moonState} state at ${data.moonIllumination}% illumination, with ${data.rashi} as lunar Rashi and ${data.solarRashi} as solar Rashi. These layers describe different parts of the day: exclusion timing, favorable-period structure and lunar background should be read together rather than collapsed into one score.`,
    `The intraday pattern adds another layer: Rahu starts ${rahuOffset} minutes after local sunrise, while ${good.length} daytime Choghadiya periods carry favorable labels${firstGood?`; the first is ${firstGood.name}`:""}. Moon illumination is ${data.moonIllumination}%, placing the date in a ${moonState} phase with the Moon in ${data.rashi}. This combination explains why the same Tithi can still produce a different practical day structure when the city, sunrise and weekday grid change.`,
    `Local timing is not represented by the lunar labels alone. Rahu enters ${rahuOffset} minutes after sunrise; the Choghadiya table contributes ${good.length} favorable-labelled windows${lastGood?`, ending with ${lastGood.name}`:""}. At the same time the Moon carries ${data.moonIllumination}% illumination in ${data.rashi}, against a solar Rashi of ${data.solarRashi}. The result is a three-layer local profile: lunar state, solar-day exclusions and weekday-derived favorable periods.`,
    `After sunrise, Rahu arrives with a ${rahuOffset}-minute offset from dawn. The daytime grid has ${good.length} favorable Choghadiya segments${firstGood&&lastGood?`, spanning from ${firstGood.name} to ${lastGood.name}`:""}. The Moon's ${data.moonIllumination}% illumination places the date in the ${moonState} class. That makes today's page locally useful in two ways: it shows when the city's exclusion clock acts and how the lunar backdrop develops through the same civil day.`,
    `Today's solar-day structure puts Rahu ${rahuOffset} minutes after sunrise. Separately, the Choghadiya sequence has ${good.length} good-labelled daytime periods${firstGood?`, beginning with ${firstGood.name}`:""}. The lunar backdrop is ${moonState}: ${data.moonIllumination}% illumination, Moon in ${data.rashi}, Sun in ${data.solarRashi}. None of those signals replaces the others; together they explain the city's practical timing shape for this date.`,
    `The city's own sunrise creates the local reference for Rahu, which begins ${rahuOffset} minutes later. The weekday sequence yields ${good.length} favorable Choghadiya periods${lastGood?`, with ${lastGood.name} as the last favorable label` :""}. Meanwhile the Moon is ${data.moonIllumination}% illuminated in ${data.rashi}. Reading these together preserves the distinction between lunar astronomy, sunrise-derived exclusions and weekday timing labels.`,
    `Rahu's local position is ${rahuOffset} minutes after sunrise. Favorable Choghadiya appears ${good.length} times in the daytime sequence${firstGood&&lastGood?`, from ${firstGood.name} through ${lastGood.name}`:""}. Moon illumination is ${data.moonIllumination}%, a ${moonState} background with ${data.rashi} lunar Rashi. This makes the daily signature more than a list of times: it describes how several independent timing systems intersect in this city's local day.`,
    `The practical clock layer starts with Rahu at a ${rahuOffset}-minute offset from sunrise. Choghadiya contributes ${good.length} favorable-labelled periods${firstGood?`, starting with ${firstGood.name}`:""}, while the Moon sits at ${data.moonIllumination}% illumination in ${data.rashi}. Taken together with ${data.solarRashi} solar Rashi, these values form the date's local timing texture without treating any single indicator as the whole Panchang.`
  ];

  return {
    title:`${city.name} local-day interpretation`,
    body:`${nativeLens} ${bodies[bodyVariant]}`,
    secondaryBody:secondary[secondVariant],
    facts:[
      {label:"Geographic frame",value:profile.geoContext,note:profile.latitudeContext},
      {label:"Solar-clock relation",value:profile.solarClockContext,note:sunrisePhase},
      {label:"Daylight shape",value:dayShape,note:`${dayMinutes} minutes`},
      {label:"Tithi transition band",value:tithiBand,note:data.tithiEnd},
      {label:"Nakshatra transition band",value:nakshatraBand,note:data.nakshatraEnd},
      {label:"Moon-light state",value:moonState,note:`${data.moonIllumination}% illumination`},
    ]
  };
}
